# Generated by Django 4.2.6 on 2025-03-18 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='farmer',
            name='aadhar_image',
            field=models.ImageField(blank=True, null=True, upload_to='aadhar_images/'),
        ),
        migrations.AddField(
            model_name='farmer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='farmer_images/'),
        ),
    ]
