# Generated by Django 4.2.6 on 2025-03-19 17:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_user_created_at_user_created_by_user_last_updated_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='aadhar_id',
            field=models.CharField(help_text='Enter a valid 12-digit Aadhar number', max_length=12, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_aadhar', message='Aadhar number must be exactly 12 digits and contain only numbers.', regex='^\\d{12}$')]),
        ),
    ]
