# Generated by Django 4.2.6 on 2025-03-20 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_dailyfarmercount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmer',
            name='aadhar_image',
            field=models.ImageField(blank=True, default='media/aadhar_images/NSCC_uwKVfC9.png', null=True, upload_to='aadhar_images/'),
        ),
        migrations.AlterField(
            model_name='farmer',
            name='image',
            field=models.ImageField(blank=True, default='media/aadhar_images/NSCC_uwKVfC9.png', null=True, upload_to='farmer_images/'),
        ),
    ]
