# Generated by Django 4.2.6 on 2025-03-21 07:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_farmer_aadhar_image_alter_farmer_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyFarmerReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('count', models.PositiveIntegerField(default=0)),
                ('block', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.block')),
                ('surveyor', models.ForeignKey(limit_choices_to={'role': 'surveyor'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('surveyor', 'month', 'year')},
            },
        ),
    ]
