# Generated by Django 4.2.6 on 2025-03-22 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_farmer_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='monthlyfarmerreport',
            unique_together={('surveyor', 'block', 'month', 'year')},
        ),
    ]
