# Generated by Django 4.2.6 on 2025-03-25 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_monthlyfarmerreport_unique_together'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('role', 'supervisor')), fields=('block',), name='unique_supervisor_per_block'),
        ),
    ]
